services:
  client:
    build:
      dockerfile: Dockerfile.client
    ports:
      # Use different port from local development
      - "127.0.0.1:5175:3000"
  server:
    build:
      dockerfile: Dockerfile.server
    ports:
      # Use different port from local development
      - "127.0.0.1:16669:16667"
